[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_resend"
version = "1.0.0"
description = "Resend.com email service integration for MindRoot"
requires-python = ">=3.9"
dependencies = [
    "resend",
    "pydantic"
]
